// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkaevutyzgpxvnbjbdwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrYWV2dXR5emdweHZuYmpiZHduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNTAzMDksImV4cCI6MjA3MTgyNjMwOX0.bcprsYJQtBS3OfN1YazPmczW39f6QOi7qz1gY1a-xN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});